(() => {
"use strict";
const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d"),$=id=>document.getElementById(id);
ctx.imageSmoothingEnabled=false;
const ui={menu:$("menu"),pause:$("pause"),difficulty:$("difficulty"),hpBar:$("hpBar"),hpText:$("hpText"),stBar:$("stBar"),stText:$("stText"),bossBar:$("bossBar"),bossPhase:$("bossPhase"),souls:$("souls"),deaths:$("deaths"),relics:$("relics"),notice:$("notice"),continueGame:$("continueGame")};
const keys=new Set(),WORLD=8200,GROUND=455,checkpoints=[120,2100,4450,6600];
let mode="menu",difficulty="normal",souls=0,deaths=0,checkpoint=0,cameraX=0,last=0,relicCount=0,victory=false,assetsReady=false,noticeTimer=0;
const images={},sources={kael:"kael-v41.png",soldier:"soldato-v41.png",hound:"segugio-v41.png",boss:"custode-v41.png",background:"bosco-v41.png",tiles:"tiles-v41.png",relics:"reliquie-v41.png"};
const P={x:120,y:407,w:32,h:48,vx:0,vy:0,speed:285,jump:670,gravity:1850,onGround:false,baseHp:120,maxHp:120,hp:120,maxSt:100,st:100,facing:1,attack:0,attackCd:0,dodge:0,dodgeCd:0,inv:0,coyote:0,jumpBuffer:0,anim:0,skillCd:0};
const platforms=[[0,455,980,100],[1060,455,680,100],[1810,455,900,100],[2790,455,600,100],[3470,455,1080,100],[4630,455,760,100],[5480,455,880,100],[6440,455,1760,100],[500,355,240,28],[1190,330,220,28],[1480,270,180,28],[2260,345,260,28],[2960,330,200,28],[3690,350,260,28],[4090,285,230,28],[4870,330,260,28],[5730,335,280,28],[6860,350,230,28],[7310,300,200,28]].map(a=>({x:a[0],y:a[1],w:a[2],h:a[3]}));
const enemies=[],pickups=[],particles=[];
function loadAssets(done){let n=0,entries=Object.entries(sources);entries.forEach(([k,src])=>{let im=new Image();im.onload=()=>{images[k]=im;if(++n===entries.length){assetsReady=true;done()}};im.onerror=()=>note("ERRORE FILE: "+src);im.src=src})}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function enemy(x,type="soldier"){let boss=type==="boss",hound=type==="hound",hp=boss?(difficulty==="fractured"?1050:760):(hound?55:80);return{type,x,y:GROUND-(boss?112:hound?32:48),w:boss?80:hound?40:32,h:boss?112:hound?32:48,vx:0,vy:0,maxHp:hp,hp,damage:boss?20:hound?10:13,phase:1,dir:-1,attackCd:0,hurt:0,dead:false,onGround:false,anim:0}}
function reset(){enemies.length=0;[720,1340,2380,3120,3820,5010,5900].forEach(x=>enemies.push(enemy(x)));[1660,3330,4250,6180].forEach(x=>enemies.push(enemy(x,"hound")));enemies.push(enemy(7560,"boss"));pickups.length=0;pickups.push({x:1410,y:235,w:24,h:24,type:0,taken:false},{x:4120,y:250,w:24,h:24,type:1,taken:false},{x:5920,y:300,w:24,h:24,type:2,taken:false})}
function frag(){let loss=difficulty==="fractured"?Math.min(.7,deaths*.05):0;P.maxHp=Math.max(36,Math.round(P.baseHp*(1-loss)));P.hp=P.maxHp}
function save(){localStorage.setItem("eclipseV41",JSON.stringify({difficulty,souls,deaths,checkpoint,relicCount}));ui.continueGame.disabled=false}
function load(){try{let d=JSON.parse(localStorage.getItem("eclipseV41")||"null");if(!d)return false;difficulty=d.difficulty||"normal";souls=d.souls||0;deaths=d.deaths||0;checkpoint=d.checkpoint||0;relicCount=d.relicCount||0;ui.difficulty.value=difficulty;return true}catch{return false}}
function note(t){ui.notice.textContent=t;ui.notice.classList.add("on");clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>ui.notice.classList.remove("on"),1800)}
function solve(b,dt){b.onGround=false;b.x+=b.vx*dt;for(const p of platforms)if(overlap(b,p)){if(b.vx>0)b.x=p.x-b.w;else if(b.vx<0)b.x=p.x+p.w;b.vx=0}b.y+=b.vy*dt;for(const p of platforms)if(overlap(b,p)){if(b.vy>0){b.y=p.y-b.h;b.vy=0;b.onGround=true}else if(b.vy<0){b.y=p.y+p.h;b.vy=0}}}
function burst(x,y,c,n=8){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*280,vy:(Math.random()-.75)*260,life:.45,color:c})}
function hurt(n,x){if(P.inv>0||mode!=="play")return;P.hp-=n;P.inv=.75;P.vx=(P.x<x?-1:1)*340;P.vy=-260;burst(P.x+16,P.y+20,"#bd3149",12);if(P.hp<=0)die()}
function attack(){if(P.attackCd>0||mode!=="play")return;P.attack=.24;P.attackCd=.34;let h={x:P.facing>0?P.x+P.w:P.x-60,y:P.y+4,w:60,h:44};enemies.forEach(e=>{if(e.dead||!overlap(h,e))return;e.hp-=e.type==="boss"?26:38;e.hurt=.14;e.vx=P.facing*190;burst(e.x+e.w/2,e.y+e.h/2,"#70b5ff",10);if(e.hp<=0){e.dead=true;souls+=e.type==="boss"?120:e.type==="hound"?5:8;if(e.type==="boss"){victory=true;mode="victory";note("IL CUSTODE È CADUTO");save()}}})}
function dodge(){if(P.dodgeCd>0||P.st<25||mode!=="play")return;P.dodge=.25;P.dodgeCd=.68;P.inv=.36;P.st-=25;P.vx=P.facing*650}
function skill(){if(P.skillCd>0||P.st<40||mode!=="play")return;P.skillCd=4;P.st-=40;burst(P.x+16,P.y+20,"#75bfff",28);let w={x:P.x-125,y:P.y-65,w:282,h:170};enemies.forEach(e=>{if(!e.dead&&overlap(w,e)){e.hp-=e.type==="boss"?38:55;if(e.hp<=0){e.dead=true;souls+=e.type==="boss"?120:10}}});note("IMPULSO D'ESSENZA")}
function die(){if(mode!=="play")return;deaths++;frag();mode="dead";note(difficulty==="fractured"?"FRAMMENTAZIONE: VITA MASSIMA -5%":"KAEL È CADUTO");setTimeout(()=>{Object.assign(P,{x:checkpoints[checkpoint],y:407,vx:0,vy:0,hp:P.maxHp,st:100,inv:1.5});reset();mode="play";save()},750)}
function start(cont=false){if(!assetsReady){note("ATTENDI IL CARICAMENTO");return}if(cont){if(!load())return}else{difficulty=ui.difficulty.value;souls=0;deaths=0;checkpoint=0;relicCount=0}victory=false;frag();Object.assign(P,{x:checkpoints[checkpoint],y:407,vx:0,vy:0,st:100,inv:0,skillCd:0});reset();mode="play";ui.menu.classList.remove("visible");note(difficulty==="fractured"?"MODALITÀ FRAMMENTATA":"IL BOSCO SEPOLTO");save()}
function updateP(dt){let l=keys.has("ArrowLeft")||keys.has("KeyA"),r=keys.has("ArrowRight")||keys.has("KeyD"),m=(r?1:0)-(l?1:0);if(m)P.facing=m;if(P.dodge<=0)P.vx+=(m*P.speed-P.vx)*Math.min(1,dt*12);P.vy+=P.gravity*dt;P.coyote=P.onGround?.1:Math.max(0,P.coyote-dt);P.jumpBuffer=Math.max(0,P.jumpBuffer-dt);if(P.jumpBuffer>0&&P.coyote>0){P.vy=-P.jump;P.coyote=0;P.jumpBuffer=0}solve(P,dt);if(P.y>620)die();P.attack=Math.max(0,P.attack-dt);P.attackCd=Math.max(0,P.attackCd-dt);P.dodge=Math.max(0,P.dodge-dt);P.dodgeCd=Math.max(0,P.dodgeCd-dt);P.inv=Math.max(0,P.inv-dt);P.skillCd=Math.max(0,P.skillCd-dt);P.st=Math.min(P.maxSt,P.st+28*dt);P.anim+=dt;checkpoints.forEach((x,i)=>{if(i>checkpoint&&Math.abs(P.x-x)<70){checkpoint=i;note("CHECKPOINT "+(i+1));save()}});pickups.forEach(p=>{if(!p.taken&&overlap(P,p)){p.taken=true;relicCount++;if(p.type===0){P.baseHp+=15;frag()}if(p.type===1)P.speed+=18;if(p.type===2){P.maxSt+=20;P.st=P.maxSt}note(["FRAMMENTO VITALE","PASSO DEL VENTO","SIGILLO D'ESSENZA"][p.type]);save()}});cameraX+=((P.x-canvas.width*.38)-cameraX)*Math.min(1,dt*5);cameraX=Math.max(0,Math.min(WORLD-canvas.width,cameraX))}
function updateE(dt){enemies.forEach(e=>{if(e.dead)return;e.attackCd=Math.max(0,e.attackCd-dt);e.hurt=Math.max(0,e.hurt-dt);e.anim+=dt;let d=P.x-e.x;if(e.type==="boss"){if(difficulty==="fractured"){let r=e.hp/e.maxHp;e.phase=r>.66?1:r>.33?2:3}else e.phase=e.hp/e.maxHp>.5?1:2;e.dir=Math.sign(d)||-1;if(Math.abs(d)>125)e.vx=e.dir*[0,105,155,215][e.phase];else e.vx*=.8;if(e.attackCd<=0&&Math.abs(d)<195){e.attackCd=[0,1.55,1.05,.72][e.phase];let reach=e.phase===3?230:165,h={x:e.dir>0?e.x+e.w:e.x-reach,y:e.y+25,w:reach,h:82};if(overlap(h,P))hurt(15+e.phase*6,e.x)}}else if(e.type==="hound"){if(Math.abs(d)<600){e.dir=Math.sign(d)||e.dir;e.vx=e.dir*145}else e.vx*=.85;if(Math.abs(d)<50&&e.attackCd<=0){e.attackCd=.9;hurt(e.damage,e.x)}}else{if(Math.abs(d)<540){e.dir=Math.sign(d)||e.dir;e.vx=e.dir*88}else e.vx*=.82;if(Math.abs(d)<58&&e.attackCd<=0){e.attackCd=1.15;hurt(e.damage,e.x)}}e.vy+=1700*dt;solve(e,dt)})}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;if(p.life<=0){particles.splice(i,1);continue}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=560*dt}}
function drawP(){if(P.inv>0&&Math.floor(P.inv*12)%2===0)return;let f=0;if(Math.abs(P.vx)>25)f=2+(Math.floor(P.anim*8)%2);if(!P.onGround)f=4;if(P.attack>0)f=P.attack>.12?5:6;if(P.dodge>0)f=7;if(P.skillCd>3.65)f=8;ctx.save();ctx.translate(P.x+16,P.y);ctx.scale(P.facing,1);ctx.drawImage(images.kael,f*32,0,32,48,-16,0,32,48);ctx.restore()}
function drawE(e){if(e.hurt>0)ctx.globalAlpha=.5;if(e.type==="boss")ctx.drawImage(images.boss,(e.phase-1)*80,0,80,112,e.x,e.y,80,112);else if(e.type==="hound"){let f=Math.floor(e.anim*8)%4;ctx.drawImage(images.hound,f*40,0,40,32,e.x,e.y,40,32)}else{let f=Math.floor(e.anim*7)%4;ctx.drawImage(images.soldier,f*32,0,32,48,e.x,e.y,32,48)}ctx.globalAlpha=1}
function draw(){ctx.drawImage(images.background,0,0,960,540);ctx.save();ctx.translate(-cameraX,0);platforms.forEach((p,i)=>{let tx=(i%8)*16;for(let x=p.x;x<p.x+p.w;x+=16)for(let y=p.y;y<p.y+p.h;y+=16)ctx.drawImage(images.tiles,tx,0,16,16,x,y,16,16)});checkpoints.forEach((x,i)=>{ctx.fillStyle=i<=checkpoint?"#69adff":"#505867";ctx.fillRect(x+10,360,5,48)});pickups.forEach(p=>{if(!p.taken)ctx.drawImage(images.relics,p.type*24,0,24,24,p.x,p.y,24,24)});enemies.forEach(e=>{if(!e.dead)drawE(e)});drawP();particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4)});ctx.globalAlpha=1;ctx.restore();if(victory){ctx.fillStyle="rgba(4,6,10,.76)";ctx.fillRect(0,0,960,540);ctx.textAlign="center";ctx.fillStyle="#eef4ff";ctx.font="bold 42px Georgia";ctx.fillText("IL BOSCO È SOPRAVVISSUTO",480,235)}}
function hud(){ui.hpBar.style.width=Math.max(0,P.hp/P.maxHp*100)+"%";ui.hpText.textContent=Math.ceil(P.hp)+"/"+P.maxHp;ui.stBar.style.width=P.st/P.maxSt*100+"%";ui.stText.textContent=Math.ceil(P.st)+"/"+P.maxSt;ui.souls.textContent=souls;ui.deaths.textContent=deaths;ui.relics.textContent=relicCount;let b=enemies.find(e=>e.type==="boss"&&!e.dead);if(b&&P.x>6900){ui.bossBar.style.width=b.hp/b.maxHp*100+"%";ui.bossPhase.textContent="Fase "+b.phase+"/"+(difficulty==="fractured"?3:2)}else{ui.bossBar.style.width="0%";ui.bossPhase.textContent="—"}}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;if(!assetsReady){ctx.fillStyle="#07090d";ctx.fillRect(0,0,960,540);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font="24px system-ui";ctx.fillText("Caricamento v4.1...",480,270);requestAnimationFrame(loop);return}if(mode==="play"){updateP(dt);updateE(dt);updateParticles(dt);hud()}draw();requestAnimationFrame(loop)}
function press(k){keys.add(k);if(k==="Space")P.jumpBuffer=.12;if(k==="KeyJ")attack();if(k==="KeyK")dodge();if(k==="KeyQ")skill();if(k==="KeyP"){if(mode==="play"){mode="pause";ui.pause.classList.add("visible")}else if(mode==="pause"){mode="play";ui.pause.classList.remove("visible")}}}
addEventListener("keydown",e=>{if(["Space","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();press(e.code)});
addEventListener("keyup",e=>keys.delete(e.code));
document.querySelectorAll(".mobile button").forEach(b=>{let k=b.dataset.key;b.addEventListener("pointerdown",e=>{e.preventDefault();b.setPointerCapture(e.pointerId);press(k)});b.addEventListener("pointerup",()=>keys.delete(k));b.addEventListener("pointercancel",()=>keys.delete(k))});
$("newGame").onclick=()=>start(false);$("continueGame").onclick=()=>start(true);$("resume").onclick=()=>{mode="play";ui.pause.classList.remove("visible")};$("quit").onclick=()=>{save();mode="menu";ui.pause.classList.remove("visible");ui.menu.classList.add("visible")};
ui.continueGame.disabled=!localStorage.getItem("eclipseV41");reset();frag();hud();loadAssets(()=>note("PROJECT ECLIPSE v4.1 PRONTO"));requestAnimationFrame(loop);
})();